ALTER TABLE "Routine"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "RoutineDayLog"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "RoutineStep"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "RoutineStepCompletion"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "WeeklyReflection"
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

ALTER TABLE "transactions"
ALTER COLUMN "id" DROP DEFAULT;
